# Generated by Django 4.0.2 on 2022-04-08 03:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='curp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='curp_invalido', message='El CURP no tiene un formato válido', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')], verbose_name='C.U.R.P.'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
