# Generated by Django 4.0.2 on 2022-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_detallearticulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallearticulos',
            name='fotos',
        ),
        migrations.AddField(
            model_name='articulos',
            name='detllas',
            field=models.ManyToManyField(to='articulos.DetalleArticulos', verbose_name='articuloImages'),
        ),
    ]
