# Generated by Django 4.0.2 on 2022-04-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_remove_detallearticulos_fotos_articulos_detllas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='detllas',
            new_name='detalles',
        ),
    ]
