# Generated by Django 4.0.2 on 2022-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_rename_detllas_articulos_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallearticulos',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
