# Generated by Django 4.0.2 on 2022-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_detallearticulos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='detalles',
            field=models.ManyToManyField(blank=True, to='articulos.DetalleArticulos', verbose_name='articuloImages'),
        ),
    ]
