# Generated by Django 4.0.2 on 2022-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_alter_articulos_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='detalles',
            field=models.ManyToManyField(blank=True, related_name='imgDetalle', to='articulos.DetalleArticulos', verbose_name='articuloImages'),
        ),
    ]
